# Generated by Django 5.2.3 on 2025-06-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_order_total_price_remove_order_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='products',
        ),
    ]
