# Generated by Django 5.2.3 on 2025-06-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_total_price_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
