# Generated by Django 5.2.3 on 2025-06-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_products_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
